linters:
  enable:
    - dupl
    - exhaustive
    - gocognit
    - gocritic
    - gofmt
    - goimports
    - ifshort
    - misspell
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - unconvert
    - whitespace
    - staticcheck
linters-settings:
  goimports:
    local-prefixes: github.com/capeprivacy
