# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/cape/
    goarch:
      - amd64
      - arm64
    binary: cape
    ldflags:
      # -s and -w were defaults in goreleaser so keeping them here.
      # I think main motivation for using them is to shrink the binary size
      # by removing unneeded symbol information.
      - -s -w -X github.com/capeprivacy/cli/cmd/cape/cmd.version={{.Version}}
    flags:
      - -tags=nonsm
archives:
  - name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    rlcp: true
    files:
      - none*
brews:
  - name: cape
    folder: Formula
    tap:
      owner: capeprivacy
      name: homebrew-tap
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
