FROM amazonlinux:2.0.20220419.0

RUN amazon-linux-extras install aws-nitro-enclaves-cli -y && \
    yum install aws-nitro-enclaves-cli-devel -y && \
    yum clean all && \
    rm -rf /var/cache/yum

ENTRYPOINT ["nitro-cli"]
