name: Main
on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup go1.19 Environment
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
      id: go
    - id: go-cache-paths
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Go dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-build }}
          ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys:
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-go-
    - name: Build and Test
      run: |
        go test ./... -race -coverprofile=coverage.out -covermode=atomic
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19.3'
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.2
          args: --timeout=3m0s --verbose
